`define SAMPLE_IO_WIDTH 	16
`define SAMPLE_WIDTH 		16
`define FILTER_COEF_WIDTH	18
`define N_BLOCKS			256

`define CLOCK_SPEED 112500000
`define SAMPLE_RATE 44100
`define CYCLES_PER_SAMPLE (`CLOCK_SPEED/`SAMPLE_RATE)

`define SPI_FIFO_LENGTH 16

//`define ENABLE_SVF
//`define ENABLE_LUTS

`define N_FILTERS 8
`define N_DELAYS  8

`define HANDLE_WIDTH 8

`define GAIN_FORMAT 5

//`define DEBUG_READS
