`default_nettype none

module top #(
		parameter n_blocks 			= 255,
		parameter data_width 		= 16,
		parameter spi_fifo_length	= 16
	) (
		`ifndef verilator
		input wire crystal,
		`else
		input wire sys_clk,
		`endif

		input  wire cs,
		input  wire mosi,
		output wire miso,
		input  wire sck,

		output wire led0,
		output wire led1,
		output wire led2,
		output wire led3,
		output wire led4,
		output wire led5,

		output wire mclk_out,
		output wire bclk_out,
		output wire lrclk_out,
		
		input  wire i2s_din,
		output wire i2s_dout,

		output wire codec_en,
		
		// "Magic" port names that the gowin compiler connects to the on-chip SDRAM
		output O_sdram_clk,
		output O_sdram_cke,
		output O_sdram_cs_n,            // chip select
		output O_sdram_cas_n,           // columns address select
		output O_sdram_ras_n,           // row address select
		output O_sdram_wen_n,           // write enable
		inout [31:0] IO_sdram_dq,       // 32 bit bidirectional data bus
		output [10:0] O_sdram_addr,     // 11 bit multiplexed address bus
		output [1:0] O_sdram_ba,        // two banks
		output [3:0] O_sdram_dqm        // 32/4
	);
	
	/**********/
	/* Engine */
	/**********/
	
	dsp_engine #(
		.n_blocks(n_blocks),
		.data_width(data_width),
		.spi_fifo_length(spi_fifo_length)
	) engine (
		.clk(sys_clk),
		.reset(reset),

		.in_sample(sample_in),
		.out_sample(sample_out),
	
		.sample_valid(sample_valid),
	
		.command_in(spi_in),
		.command_in_valid(spi_in_valid),

		.current_pipeline(current_pipeline),
		
		.out(out),
		.spi_byte_out(spi_byte_out),

		.sdram_read(sdram_read),
		.sdram_write(sdram_write),
		.sdram_refresh(sdram_refresh),
		.addr_to_sdram(addr_to_sdram),
		.data_to_sdram(data_to_sdram),
		.data_from_sdram(data_from_sdram),

		.sdram_data_valid(sdram_data_valid),
		.sdram_busy(sdram_busy)
	);
	
	wire [7:0] out;
	wire [7:0] spi_byte_out;
	
	wire current_pipeline;
	
	wire reset = ~pll_lock;
	
	/***********/
	/*   I/O   */
	/***********/

	// Useful LED indicators (active low)
	assign led0 = ~current_pipeline;
	assign led1 = ~out[0];
	assign led3 = ~out[1];
	assign led4 = ~out[2];
	assign led5 = ~out[3];

	// I2S
	wire sample_valid;

	wire [data_width - 1 : 0] sample_out;
	wire [data_width - 1 : 0] sample_in;

	i2s_trx #(.sample_size(data_width)) i2s_driver (
		.sys_clk(sys_clk), .bclk(bclk), .lrclk(lrclk), .din(i2s_din), .dout(i2s_dout),
		.enable(1'b1), .reset(reset), .rx_valid(sample_valid),
		.tx_l(sample_out), .tx_r(sample_out),
		.rx_l(sample_in), .rx_r()
	);
	
	// SPI
	wire [7:0] spi_in;
	wire spi_in_valid;
	
	reg  [4:0] spi_byte_ctr = 0;

	sync_spi_slave spi (
		.clk(sys_clk),
		.reset(reset),

		.sck(sck),
		.cs(cs),
		.mosi(mosi),
		.miso(miso),
		.miso_byte(spi_byte_out),

		.enable(1),

		.mosi_byte(spi_in),
		.data_valid(spi_in_valid)
	);
	
	// Enable power supply to codec when PLL is locked
	assign codec_en = pll_lock;
	
	/**********/
	/* Clocks */
	/**********/
	
	`ifndef verilator // Non-simulated; use crystal and PLL
	wire sys_clk;
	wire pll_lock;
	
	/* PLL to generate main clock from crystal */
	Gowin_rPLL pll(
		.clkout(sys_clk),
		.clkin(crystal),
		.lock(pll_lock)
	);
	`else // Simulated; clock is generated by simulator
	reg pll_lock = 0;
	
	always @(posedge sys_clk)
		pll_lock <= 1;
	`endif

	/* I2S clocks */
	reg mclk = 1'b0;
	reg bclk = 1'b0;
	wire lrclk;
	
	reg [2:0] mclk_ctr = 0;
	reg [3:0] bclk_counter = 4'd0;
	
	reg [5:0] lrclk_counter = 6'd0;
	assign lrclk = lrclk_counter[5];
	
	assign mclk_out  = mclk;
	assign bclk_out  = bclk;
	assign lrclk_out = lrclk;
	
	always @(posedge sys_clk) begin
		if (pll_lock) begin
			if (mclk_ctr == 4) begin
				mclk <= ~mclk;
				mclk_ctr <= 0;

				bclk_counter <= bclk_counter + 1'b1;
				if (bclk_counter == 1) begin
					bclk <= ~bclk;
					bclk_counter <= 0;

					if (bclk)
						lrclk_counter <= lrclk_counter + 1;
					end
			end else begin
				mclk_ctr <= mclk_ctr + 1;
			end
		end   
	end
	
	wire clk_sdram;
	
	wire sdram_read;
	wire sdram_write;
	wire sdram_refresh;
	wire [21 : 0] addr_to_sdram;
	wire [data_width - 1 : 0] data_to_sdram;
	wire [data_width - 1 : 0] data_from_sdram;

	wire sdram_data_valid;
	wire sdram_busy;
	
	sdram  #(
			.data_width(data_width),
			
			.FREQ(112_500_000),
			
			.ROW_WIDTH(11),
			.COL_WIDTH(8),
			.BANK_WIDTH(2),  

			.CAS(4'd4),     
			.T_WR(4'd4),
			.T_MRD(4'd4),
			.T_RP(4'd2),
			.T_RCD(4'd2),
			.T_RC(4'd8)
		)
		sdram_controller
		(
			.SDRAM_DQ(IO_sdram_dq),     // 32 bit bidirectional data bus
			.SDRAM_A(O_sdram_addr),     // 11 bit multiplexed address bus
			.SDRAM_BA(O_sdram_ba),      // 4 banks
			.SDRAM_nCS(O_sdram_cs_n),   // a single chip select
			.SDRAM_nWE(O_sdram_wen_n),  // write enable
			.SDRAM_nRAS(O_sdram_ras_n), // row address select
			.SDRAM_nCAS(O_sdram_cas_n), // columns address select
			.SDRAM_CLK(O_sdram_clk),
			.SDRAM_CKE(O_sdram_cke),
			.SDRAM_DQM(O_sdram_dqm),
			
			.clk(sys_clk),
			.clk_sdram(clk_sdram),
			.resetn(~reset),
			.rd(sdram_read),
			.wr(sdram_write),
			.refresh(sdram_refresh),
			.addr(addr_to_sdram),
			.din(data_to_sdram),
			.dout(data_from_sdram),
			.dout32(),
			.data_ready(sdram_data_valid),
			.busy(sdram_busy)
		);
endmodule

`default_nettype wire
